/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/chair.gltf
*/
import * as THREE from 'three';
import { useGLTF, useTexture,   } from '@react-three/drei'
import { useCustomization } from '../../contexts/Customization';


export function Floor() {
  const {material} = useCustomization();

 
  const tacoReto = useTexture({
    map: "/textures/taco/Wood_Floor_012_basecolor.jpg",
    normalMap: "/textures/taco/Wood_Floor_012_normal.jpg",
    roughnessMap: "/textures/taco/Wood_Floor_012_roughness.jpg",
    aoMap: "/textures/taco/Wood_Floor_012_ambientOcclusion.jpg",
  });
  tacoReto.map.repeat.set(3,3)
  tacoReto.normalMap.repeat.set(3,3)
  tacoReto.roughnessMap.repeat.set(3,3)
  tacoReto.aoMap.repeat.set(3,3)

  tacoReto.map.wrapS = THREE.RepeatWrapping
    tacoReto.map.wrapT =  THREE.RepeatWrapping
    tacoReto.normalMap.wrapS = THREE.RepeatWrapping
    tacoReto.normalMap.wrapT =THREE.RepeatWrapping
    tacoReto.roughnessMap.wrapS = THREE.RepeatWrapping
    tacoReto.roughnessMap.wrapT =THREE.RepeatWrapping
    tacoReto.aoMap.wrapS =THREE.RepeatWrapping
    tacoReto.aoMap.wrapT = THREE.RepeatWrapping

    const tacoQuadrado = useTexture({
      map: "/textures/taco_encaixado/Substance_Graph_BaseColor.jpg",
      normalMap: "/textures/taco_encaixado/Substance_Graph_Normal.jpg",
      roughnessMap: "/textures/taco_encaixado/Substance_Graph_Roughness.jpg",
      aoMap: "/textures/taco_encaixado/Substance_Graph_AmbientOcclusion.jpg",
    });
    tacoQuadrado.map.repeat.set(3,3)
    tacoQuadrado.normalMap.repeat.set(3,3)
    tacoQuadrado.roughnessMap.repeat.set(3,3)
    tacoQuadrado.aoMap.repeat.set(3,3)

    tacoQuadrado.map.wrapS = THREE.RepeatWrapping
      tacoQuadrado.map.wrapT = THREE.RepeatWrapping  
      tacoQuadrado.normalMap.wrapS = THREE.RepeatWrapping 
      tacoQuadrado.normalMap.wrapT = THREE.RepeatWrapping
      tacoQuadrado.roughnessMap.wrapS = THREE.RepeatWrapping 
      tacoQuadrado.roughnessMap.wrapT = THREE.RepeatWrapping
      tacoQuadrado.aoMap.wrapS = THREE.RepeatWrapping
      tacoQuadrado.aoMap.wrapT = THREE.RepeatWrapping 
   
    
  
  return (
    <mesh rotation={[-90, 0, 0]}>
      <planeGeometry args={[43, 32]} />
      <meshStandardMaterial {...material === "tacoReto" ? tacoReto : tacoQuadrado}  side={THREE.DoubleSide} />
    </mesh>
  )
}

useGLTF.preload('./models/chair.gltf')
